### ISSUE TITLE
Opção de utilizar SSH ou FTP para conectar-se ao Mikrotik

### ISSUE THREAD

**Issue by brlink-org** [brlink-org/bckp-mikrotik-email-telegram.sh#5]
Pode ser mais conveniente, ao invés de usar o SSH utilizar o protocolo FTP como método de conexão ao Mikrotik para fazer o donwload do arquivo.

**Comment by cirinho** [comment]
Pode substituir o SSH pelo FTP já utilizo em produção com algo do tipo:
```
# Conecta-se ao Mikrotik via FTP
ftp -in $MK_IP <<END_SCRIPT
quote USER $MK_USER
quote PASS $MK_PASS
get $MK_BCKP_FILE
quit
END_SCRIPT
```

**Comment by cirinho** [comment]
Porém o ideal seria colocar a opção em uma variável para escolher SSH ou FTP similar ao método de compactação ZIP ou TAR

**Comment by cirinho** [comment]
> # Conecta-se ao Mikrotik via FTP
> ftp -in $MK_IP <<END_SCRIPT
> quote USER $MK_USER
> quote PASS $MK_PASS
> get $MK_BCKP_FILE
> quit
> END_SCRIPT

Infelizmente via FTP somente pode fazer o download do arquivo de backup, não tem como executar comandos dentro do Mikrotik como por exemplo enviar arquivo por e-mail pelo próprio Mikrotik.

**Comment by brlink-org** [comment]
> Infelizmente via FTP somente pode fazer o download do arquivo de backup, não tem como executar comandos dentro do Mikrotik como por exemplo enviar arquivo por e-mail pelo próprio Mikrotik.

Se não envia por e-mail perde uma das funções que o script se propõe, nesse caso então não vale a pena trocar a opção de SSH para FTP. Vamos encerrar esta questão.

**Comment by cirinho** [comment]
Sendo assim vou acrescentar no código comentado a opção do FTP assim quem desejar utilizar pode remover o comentário.
